name: Setup Gradle

inputs:
  dependency-graph:
    required: false
    default: generate-and-upload

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        dependency-graph: ${{ inputs.dependency-graph }}
