name: Full E2E test

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build
    uses: ./.github/workflows/nightly.yml
  test:
    name: E2E test
    needs: build
    strategy:
      fail-fast: false
      matrix:
        version:
          - 1.19.3
          - 1.18.2
          - 1.17.1
          - 1.16.5
          - 1.15.2
          - 1.14.4
          - 1.13.2
          - 1.12.2
          - 1.11.2
          - 1.10.2
          - 1.9.4
          - 1.8.9
        proxy:
          - velocity
          - bungeecord
          - waterfall
    uses: ./.github/workflows/e2e_test.yml
    with:
      proxy: ${{ matrix.proxy }}
      version: ${{ matrix.version }}
