name: Modrinth release

on: workflow_dispatch

env:
  MODRINTH_UPLOAD: true
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

jobs:
  version:
    name: Detect version
    uses: ./.github/workflows/version.yml
  upload:
    name: Build and upload
    needs: version
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.version.outputs.version }}
