name: Modrinth release

on: workflow_dispatch

jobs:
  version:
    name: Detect version
    uses: ./.github/workflows/version.yml
  upload:
    name: Build and upload
    needs: version
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.version.outputs.version }}
      modrinth-upload: true
    secrets:
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
