name: Nightly build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'
  workflow_call:

jobs:
  prepare:
    name: Prepare
    outputs:
      version: ${{ steps.sha8.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate version string
        id: sha8
        run: |
          SHA=${{ github.sha }}
          SHA8=${SHA:0:8}
          echo "SHA8 = $SHA8"
          echo "version=0.0.0+$SHA8" >> $GITHUB_OUTPUT
  build:
    name: Build
    needs: prepare
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.prepare.outputs.version }}
